version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: nsfminer-{{ .Environment.CACHE_VERSION }}


  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.hunter
          key: nsfminer-{{ .Environment.CACHE_VERSION }}

  build:
    steps:
      - run: ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - run: apt update
      - run: apt install -y git cmake mesa-common-dev libdbus-1-dev
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache_cmd
      - run: cmake -DHUNTER_JOBS_NUMBER=4 -H. -Bbuild
      - run: cmake --build build -- -j4
      - save_cache_cmd
      - store_artifacts:
          path: build/nsfminer/nsfminer
          destination: nsfminer

executors:
 docker-executor-u20n10:
   docker:
     - image: nvidia/cuda:10.0-base-ubuntu18.04

jobs:
  build-with-docker-u20n10:
    executor: docker-executor-u20n10
    steps:
      - build
    environment:
        TZ: "America/New_York"

workflows:
  build-with-docker:
    jobs:
      - build-with-docker-u20n10

